### PR TITLE
Adds ability to return default value if path is undefined.

### PR DESCRIPTION
**Pull request by manovotny**
I know this might be beyond the scope of this project, but I thought I'd give it a try anyway. No offense if you don't feel it's right for the project.

This PR adds the ability to return a default value if the nested object path does not exist. 

It will still return `undefined`, by default, but now a user can supply a value to be returned instead.

A new test has been added and all existing tests pass.

The readme has also been updated with new examples and api explanation.

Please let me know if you want / need anything else from me.

Thanks for the consideration!

### CODE REVIEW

**Comment by stevemao** [comment]
I'd suggest you have a look at https://github.com/mariocasciaro/object-path. This utility module is supposed to be simple. I'd just do `dotProp.get({foo: {bar: 'a'}}, 'foo.notDefined.deep') || 'default'`

**Comment by manovotny** [comment]
Thanks for the reply!

I am aware of `object-path` and I have been using the same code you provided.

I didn't make assume that you'd want this to be a part of the module, but thought I'd whip up a PR with a convenience parameter on the `get` method.

Like I said above, If you'd rather keep it out of `dot-prop`, I will take no offense and you can close the PR.

**Comment by sindresorhus** [comment]
I like it. `||` would fail in case of a falsy value:

```js
dotProp.get({foo: {bar: 0}}, 'foo.bar') || 'fail';
//=> 'fail'
```

You could use a ternary, but that's verbose.

**Comment by manovotny** [comment]
@sindresorhus : : 

I hadn't even thought about the falsy value / use case. 

That's an even better reason to implement this, IMO.

**Comment by sindresorhus** [comment]
@manovotny I had to revert this as it broke when merged to master. Would you be able to do another PR?

**Comment by manovotny** [comment]
@sindresorhus : : 

You bet! I see the early return from the newer `Object.prototype.propertyIsEnumerable` is probably what threw things off.

**Comment by manovotny** [comment]
#31 is in play now to replace this PR.

**Pull request merged**
