### PR TITLE
Accept escaped dots in path

### PR DESCRIPTION
**Pull request by floatdrop**
Alternative of #7 

Allow escaped dots (`\\.`) in paths.

### CODE REVIEW

**Comment by stevemao** [comment]
I like escape notation better because the argument is the same type as none escaped path. It also looks cooler. I don't know why people put `.` in the variable name so I don't think we need another argument type for something that's not used very often.

I would change and cache the regex. 
```js
var rpaths = /(?:\\.|[^.])+/g;
var rescapedDots = /\\\./g;
```

**Comment by sindresorhus** [comment]
@floatdrop friendly ping :)

**Comment by floatdrop** [comment]
@sindresorhus rebased.

I make a [benchmark](https://gist.github.com/floatdrop/c4cbe0a90a084373653c) to see performance of regex and it became __twice__ slower:

```
Original version:
       3,407,532 op/s » get a
       3,269,864 op/s » get a.b
       2,624,356 op/s » get a.b.c
       2,319,809 op/s » get a.b.c.d
       2,021,456 op/s » get a.b.c.d.e
       1,797,072 op/s » get a.b.c.d.e.f

Escaped dots:
       1,241,859 op/s » get a
       1,236,366 op/s » get a.b
         986,551 op/s » get a.b.c
         823,443 op/s » get a.b.c.d
         607,857 op/s » get a.b.c.d.e
         604,458 op/s » get a.b.c.d.e.f
```

**Comment by stevemao** [comment]
Depends on the use cases I guess. performance vs cool syntax.

**Comment by floatdrop** [comment]
@stevemao yep. But maybe it is worth trying to split strings without regex - because `get` operation can be quite hot and I don't want it to be a bottleneck.

P.s. Sorry for long absence - lost of stuff at one time. Will dig it on next week :dog:

**Comment by stevemao** [comment]
Oh very true. There will be a regression even if you don't have escaped `.` in path.

**Comment by sindresorhus** [comment]
It's still super fast though. I can't think of any use-case these differences will matter at all.

Could always look at how Lodash does it: https://github.com/lodash/lodash/blob/226256c269d0f101fe41ae7eced6e93b26ddcdf4/lodash.js#L2071

**Comment by floatdrop** [comment]
@sindresorhus lodash uses Array for passing props with dots. This feature is not quite popular - so I don't see a reason to have penalty for nothing.

**Comment by sindresorhus** [comment]
Could we check if there's an escaped dot in the string, if so go the advanced route, otherwise just simply split?

**Comment by floatdrop** [comment]
@sindresorhus good idea. Other option split by `.` always and check that last char in string is `\`. More benchmarks are coming. :)

**Comment by floatdrop** [comment]
```
Split and concat:
       5,373,108 op/s » get a
       8,286,555 op/s » get a.b
       7,276,163 op/s » get a.b.c
       6,588,286 op/s » get a.b.c.d
       6,231,897 op/s » get a.b.c.d.e
       5,777,333 op/s » get a.b.c.d.e.f
```

**Comment by stevemao** [comment]
How come the "split and concat" is faster than the original? also getting `a.b` is faster than `a`.

**Comment by floatdrop** [comment]
@stevemao `some` and `forEach` are bad for v8 optimizations (it will be better soon). But I'm not sure why `a` is slower than `a.b` - even if I run benchmark multiple times in a row - it not gain performance from v8 optimizer. I have wild guess, that `split` can be slower in case of no `.` occurrence.

**Comment by floatdrop** [comment]
So... Seems like splitting string without `.` by `.` is not great idea in V8 - https://jsperf.com/splitwtf

```
                      get
      21,466,786 op/s » a
       5,419,010 op/s » a.b
       5,339,380 op/s » a.b.c
       5,038,595 op/s » a.b.c.d
       4,730,591 op/s » a.b.c.d.e
       4,464,890 op/s » a.b.c.d.e.f

                      set
      19,177,541 op/s » a
       4,786,524 op/s » a.b
       4,499,128 op/s » a.b.c
       4,041,281 op/s » a.b.c.d
       3,816,204 op/s » a.b.c.d.e
       3,594,263 op/s » a.b.c.d.e.f
```

@sindresorhus what do you think?

**Comment by sindresorhus** [comment]
Doesn't really matter. These are super good numbers and this is really just a premature optimization. I think what we got is super. Do you mind adding a readme note about supporting escaped dots?

**Comment by floatdrop** [comment]
@sindresorhus added example in usage.

**Comment by sindresorhus** [comment]
Awesome! Thanks dude :)

And thanks for reviewing @stevemao

**Comment by stevemao** [comment]
:smile:

**Pull request closed without merging**
