### PR TITLE
Allow getting non-enumerable properties

### LINKED ISSUE #46: get() method's switch to object.prototype.propertyIsEnumerable broke my code
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/dot-prop/issues/46)

This change was made in July 2016:

    use `object.prototype.propertyIsEnumerable instead of `Object.getOwnPropertyDescriptor`

Unfortunately, this change broke my code. Specifically, I was using it like this in the [Express](http://expressjs.com/) framework:

    dot = require( "dot-prop" );
    req.app.locals.foo = 1;
    console.log( "foo = " + dot.get( req, "app.locals.foo" ) );

where the `req` object is defined [here](http://expressjs.com/en/4x/api.html#req).

Before this change, `foo = 1` was logged.
After this change, `foo = undefined` was logged.

The problem appears to be that `req.app` isn't an enumerable property because it is an **inherited** property.

So, here's my question: why are we discriminating against inherited properties inside the `get()` method? That doesn't seem right to me.

> There is a $40.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/dot-prop/issues/46).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/dot-prop/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by stroncium**
Changes the way to check property for enumerability, fixes #46

### CODE REVIEW

**Comment by stroncium** [comment]
Sidenote, no code around enumerability was ever applied to anything but `get`.

**Comment by sindresorhus** [comment]
I need your opinion; does it really make sense to check enumerability at all? I just read through the original issue about it (https://github.com/sindresorhus/dot-prop/issues/23) and I'm not sure I buy the argument anymore. Also, it's weird that the check is only applied to `get` and not the other methods.

**Comment by stroncium** [comment]
Con: it really does work different from normal object access(obviously ignoring whole exception vs `undefined` part there). But I can hardly imagine real world situations when people want to read properties flagged non-enumerable using this lib, and if they do their design will clearly considered by most to be really bad.

Pro: it actually seems to better match expectations and frequent use-cases. This bug is about inherited properties and it makes sense it should read inherited properties. For the other cases, it silently protects from sometimes hard to trace bugs.

All in all, I'd say I'm for doing enumerability checks.

Logic should probably be applied to all methods, yeah. (Though logic will always be weirdly different between reading and modifying methods for prototypes.)

**Comment by stevemao** [comment]
I vote for removing related code of enumerability.

**Comment by stroncium** [comment]
@sindresorhus So, what are we going for there? Removal of enumerability checks or unifying method behavior?

**Comment by lselden** [comment]
@sindresorhus Request to get this merged, though I understand it might qualify as a major release bump. I don't see any reason that a value's enumerable value should matter if someone explicitly tries to access it using .get / .has

**Review by ermanzohre — APPROVED** [review]

**Comment by sindresorhus** [comment]
Remove the enumerability checks.

**Review by ermanzohre — APPROVED** [review]

**Comment by stroncium** [comment]
Side note, I feel like this package could use a bit more tests. Nothing exact of the top of my head, but I can't believe existing ones cover all the tricky stuff.

**Comment by sindresorhus** [comment]
@stroncium Comment in https://github.com/sindresorhus/dot-prop/issues/70 if you have any ideas of what the tests might be.

**Pull request merged**
