### PR TITLE
backslash in prop should work

### LINKED ISSUE #15: support of backslashes in properties?
how to access a property like `'a\\b'`? 

these getter tests fail:
```javascript
t.is(m.get({'\\': true}, '\\\\'), true);
t.is(m.get({'a\\b': true}, 'a\\\\b'), true);
t.is(m.get({'fo\\.ob.az': {bar: true}}, 'fo\\\\\\.ob\\.az.bar'), true);
```

### PR DESCRIPTION
**Pull request by stevemao**
Fixes #15

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I tried to fix this issue as well, but instead tried using a regex to split the string which results in much cleaner code.

```js
	var pathArr = path.split(/[^\\\\]\./);

	for (var i = 0; i < pathArr.length; i++) {
		obj = obj[pathArr[i]];

		if (obj === undefined) {
			break;
		}
	}
```

The downside is that it isn't working entirely (yet) as it eats up the last character per token.

```
'foo\\.bar.baz'.split(/[^\\\\]\./);
//=> [ 'foo\\.ba', 'bar' ]
```

I was looking into using something like a lookbehind/lookahead, but I'm not very familiar with the concept. Just wanted to share because maybe someone else has an idea to simplify this.

**Comment by stevemao** [comment]
I tried to use a customised `split` (parse the string manually).
We should set up benchmark to see which solution is the best.

**Comment by hobbyquaker** [comment]
here my approach to a split function. Backslash can escape dots and backslashes.

```javascript
        /**
         * Split str by dot - supports backslash escaped dots and backslashes
         * @param {string} str
         * @returns {Array.<string>}
         */
        function split(str) {
            str = '' + str;

            if (str.indexOf('\\.') === -1) return str.split('.');

            var res = [];
            var pos = 0;
            var esc;

            function chunk(start, end) {
                // slice, unescape and push onto result array. set position of next chunk.
                res.push(str.slice(start, end).replace(/\\\\/g, '\\').replace(/\\\./g, '.'));
                pos = end + 1;
            }

            var j;
            for (var i = 0, l = str.length; i < l; i++) {
                if (str[i] === '.') {
                    esc = false;
                    // walk over preceding backslashes in reverse direction
                    for (j = i - 1; str[j] === '\\'; j--) esc = !esc;
                    // dot is escaped only if preceded by an odd number of backslashes
                    if (!esc) chunk(pos, i);
                }
            }

            chunk(pos, i);

            return res;
        }
```

**Comment by stevemao** [comment]
@hobbyquaker Can you do a PR and we can benchmark it. Thanks.

**Comment by hobbyquaker** [comment]
will do tomorrow :)

**Comment by hobbyquaker** [comment]
I just compared my split method, as expected is it much slower...

getPathSegments from current master branch:
```
         171,953 op/s » get
          75,894 op/s » set
          61,423 op/s » delete
```

my implementation:
```
          88,625 op/s » get
          44,889 op/s » set
          33,033 op/s » delete
```

But I think these results aren't really comparable. Current implementation only escapes dots and would fail on some edge cases like f.e. `t.is(m.get({'fo\\.ob.az\\': {bar: true}}, 'fo\\\\.ob\\.az\\.bar'), true);`

I would suggest before comparing performance we should clearify the escape-behaviour. I think only escaping dots (like statet in #18) isn't enough. Imho backslashes themselves have to be escaped too.

**Comment by stevemao** [comment]
Can you do a PR? The current tests are not complete.

**Comment by sindresorhus** [comment]
ping @hobbyquaker :)

**Comment by stevemao** [comment]
Can we merge this and if anyone can make a faster implementation, do a follow-up PR.

**Pull request merged**
