### PR TITLE
Accept Array in path

### PR DESCRIPTION
**Pull request by floatdrop**
This will allow to access props with `.` in names (also will stop split/join madness on each call).

### CODE REVIEW

**Comment by kevva** [comment]
Hm, it's a little weird two expose two APIs but I guess it makes sense if you want to access props with `.`. @sindresorhus, wdyt?

**Comment by sindresorhus** [comment]
I want to support this somehow, but not a big fan of this API. Not sure there are any better ways though. How about being able to escape the dot instead?

```js
dotProp({foo: {'foo.bar': 'unicorn'}}, 'foo.foo\\.bar');
```

**Comment by kevva** [comment]
That's better imo.

**Comment by sindresorhus** [comment]
@floatdrop thoughts?

**Comment by floatdrop** [comment]
@sindresorhus this could be done either way - I'm just waiting for https://github.com/sindresorhus/dot-prop/pull/6 to rebase agains it.

With escaping sequence I will need to split path (we storing fs-like structure in object) and rejoin it with `\\.`. I don't have any perf tests of it, but imho this would be slower. But, again, we recreate this object not often.

**Pull request closed without merging**
